AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'IAM Configuration'
        Parameters:
          - BucketName
          - GithubRepositoryName
          - OIDCThumbprint

Parameters:
  BucketName:
    Type: String
    Default: resources
  GithubRepositoryName:
    Type: String
    Default: grim13b/cicd-for-gha
  OIDCThumbprint:
    Type: CommaDelimitedList
    Default: '6938fd4d98bab03faadb97b34396831e3780aea1'

Resources:
  AssumeDeployRoleForGithubOIDC:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      RoleName: AssumeDeployRoleForGithubOIDC
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRoleWithWebIdentity'
            Principal:
              Federated: !Ref Oidc
            Condition:
              # 条件は適宜必要なものを指定する
              # https://docs.github.com/ja/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#configuring-the-oidc-trust-with-the-cloud
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - !Sub 'repo:${RepositoryName}:*'
      Policies:
        - PolicyName: AllowGithubActionsDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                  - 's3:ListObject'
                Resource:
                  - !Sub 'arn:aws:s3:::${BucketName}'
                  - !Sub 'arn:aws:s3:::${BucketName}/*'

  Oidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: [sts.amazonaws.com]
      ThumbprintList: !Ref OIDCThumbprint

Outputs:
  AssumeDeployRoleForGithubOIDC:
    Value: !Ref AssumeDeployRoleForGithubOIDC

  AssumeDeployRoleForGithubOIDCARN:
    Value: !GetAtt AssumeDeployRoleForGithubOIDC.Arn